[platform_archives.cmake.macos_x86_64]
url = "https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-macos-universal.tar.gz"
sha256 = "c6fdda745f9ce69bca048e91955c7d043ba905d6388a62e0ff52b681ac17183c"
add_prefix = "{{spaces.sysroot}}"
strip_prefix = "cmake-3.30.2-macos-universal/CMake.app/Contents/"
includes = [
    "cmake-3.30.2-macos-universal/CMake.app/Contents/bin/**",
    "cmake-3.30.2-macos-universal/CMake.app/Contents/Plugins/**",
    "cmake-3.30.2-macos-universal/CMake.app/Contents/share/**",
]
link = "Hard"

[platform_archives.cmake.macos_aarch64]
url = "https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-macos-universal.tar.gz"
sha256 = "c6fdda745f9ce69bca048e91955c7d043ba905d6388a62e0ff52b681ac17183c"
add_prefix = "{{spaces.sysroot}}"
strip_prefix = "cmake-3.30.2-macos-universal/CMake.app/Contents/"
includes = [
    "cmake-3.30.2-macos-universal/CMake.app/Contents/bin/**",
    "cmake-3.30.2-macos-universal/CMake.app/Contents/Plugins/**",
    "cmake-3.30.2-macos-universal/CMake.app/Contents/share/**",
]
link = "Hard"

[vscode.extensions]
recommendations = ["twxs.cmake"]
