[platform_archives.cmake.macos_x86_64]
url = "https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-macos-universal.tar.gz"
sha256 = "c6fdda745f9ce69bca048e91955c7d043ba905d6388a62e0ff52b681ac17183c"
add_prefix = "{{spaces.sysroot}}"
strip_prefix = "cmake-3.30.2-macos-universal/CMake.app/Contents/"
link = "Hard"

[platform_archives.cmake.macos_aarch64]
url = "https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-macos-universal.tar.gz"
sha256 = "c6fdda745f9ce69bca048e91955c7d043ba905d6388a62e0ff52b681ac17183c"
add_prefix = "{{spaces.sysroot}}"
strip_prefix = "cmake-3.30.2-macos-universal/CMake.app/Contents/"
link = "Hard"

[platform_archives.cmake.linux_x86_64]
url = "https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-linux-x86_64.tar.gz"
sha256 = "cdd7fb352605cee3ae53b0e18b5929b642900e33d6b0173e19f6d4f2067ebf16"
add_prefix = "{{spaces.sysroot}}/bin"
link = "Hard"

[platform_archives.cmake.windows_x86_64]
url = "https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-windows-x86_64.zip"
sha256 = "48bf4b3dc2d668c578e0884cac7878e146b036ca6b5ce4f8b5572f861b004c25"
add_prefix = "{{spaces.sysroot}}/bin"
link = "Hard"